name: 'Get Merged Pull Requests'
description: 'Compare two tags and retrieve all the pull requests merged between them.'
author: 'Van Ons'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  github_token:
    description: 'The GitHub token to use.'
    required: true
  repo:
    description: 'The repository to use. Defaults to current repository. Expected format: `owner/repo`.'
    required: false
  current_tag:
    description: 'The current tag to use. Defaults to current/latest tag.'
    required: false
  previous_tag:
    description: 'The previous tag to use. Defaults to one tag before the current tag.'
    required: false
  return_type:
    description: 'What data to return. Options are: `title_only`, `all`.'
    required: false
    default: 'title_only'
  commit_is_pull_request_regex:
    description: "The regex to use to determine if a commit is a pull request merge commit. This is checked against a commit's title. Default regex: `^Merge pull request.*`."
    required: false
  apply_commit_is_pull_request_regex:
    description: 'Whether to apply `commit_is_pull_request_regex` to the commits.'
    required: false
    default: false
  pull_request_regex:
    description: "The regex to use if you want to filter the pull requests. This is checked against a pull request's title. Example regex: `^\\[Feat].*`."
    required: false
outputs:
  pull_requests:
    description: 'The pull requests merged between the two tags.'
runs:
  using: node20
  main: dist/index.js
