name: Get merged pull requests

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#      - main
#      - 'releases/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get merged pull requests
        uses: ./
        id: pull-requests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          repo: ${{ github.repository }}
#          current_tag: ${{ github.ref }}
#          previous_tag: ${{ github.ref }}
#          return_type: all
      - name: Print merged pull requests
        run: |
          echo "Pull requests:\n"
          echo "${{ steps.pull-requests.outputs.pull_requests }}"
