name: Get merged pull requests

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches:
#      - main
#      - 'releases/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get merged pull requests
        uses: ./
        id: pull_requests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          repo: ${{ github.repository }}
#          current_tag: ${{ github.ref }}
#          previous_tag: ${{ github.ref }}
#          return_type: all
      - name: Print merged pull requests
        run: |
          pull_requests="${{ steps.pull_requests.outputs.pull_requests }}"
          if [ -z "$pull_requests" ]; then
            echo "The following pull requests were merged between the current and previous tag:"
            echo "$pull_requests" | jq -r '.[].title' | while read -r title; do
              echo "- $title"
            done
          else
            echo "No pull requests were merged between the current and previous tag."
          fi
